### ISSUE TITLE
SPARQL syntax error in SELECT DISTINCT COUNT(*) AS...

### ISSUE THREAD

**Issue by TallTed** [OpenLinkSoftware/single-page-apps#9]
[Here](https://github.com/OpenLinkSoftware/single-page-apps/blob/3d63bf29e7529efaa5aac361f99058427d22b8b4/data-entry-form.html#L983) and elsewhere, `SELECT DISTINCT COUNT(*) AS ?count` is incorrect.
* Aliased aggregate within SPARQL `SELECT` requires wrapping in parentheses.
* `DISTINCT COUNT` doesn't make sense.

Possible corrections include --
* `SELECT ( COUNT(DISTINCT *) AS ?count )`
* `SELECT ( COUNT(*) AS ?count )`

**Comment by openlink** [comment]
I do not see any syntax error here. Note [this SPARQL Query solution page](http://linkeddata.uriburner.com/sparql?default-graph-uri=&query=SELECT+DISTINCT+COUNT%28*%29+AS+%3Fcount+FROM+%3Curn%3Arecords%3Atest%3E+WHERE+%7B%3Fsubject+%3Fpredicate+%3Fobject%7D&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000000). 

Bearing in mind this app is partly for educational purposes, best practices are important, so I will apply a fix.

**Comment by TallTed** [comment]
SPARQL syntax requires the wrapper on the aggregate `COUNT`; it's not just best practice.  Virtuoso forgives and handles the construction above, but it remains a SPARQL syntax error.
